name: Deploy Docs

on:
  push:
    branches:
      - main  # or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        run: pip install uv

      - name: Install dependencies
        run: uv pip install sphinx sphinx-rtd-theme

      - name: Build HTML
        run: sphinx-build -b html -c docs docs docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
